### PR TITLE
Add initial setup of PHPUnit

### PR DESCRIPTION
**Pull request by robtownsend1**

### CODE REVIEW

**Comment by danalamo** [comment]
@robtownsend1 can you post a screenshot of the local successful setup on these?

**Comment by robtownsend1** [comment]
> @robtownsend1 can you post a screenshot of the local successful setup on these?

@danalamo Do you mean the output of running `phpunit`?

**Comment by danalamo** [comment]
> > @robtownsend1 can you post a screenshot of the local successful setup on these?
> 
> @danalamo Do you mean the output of running `phpunit`?

Sorry, yes, that's what I mean

**Comment by robtownsend1** [comment]
> > > @robtownsend1 can you post a screenshot of the local successful setup on these?
> > 
> > 
> > @danalamo Do you mean the output of running `phpunit`?
> 
> Sorry, yes, that's what I mean

Sure here it is:

image

**Review by danalamo — APPROVED** [review]

**Pull request merged**
